chore(release): v0.3.2 (#15)
* ci: update workflow

* ci: update

* chore(release): v0.3.2

Automatically generated by python-semantic-release

---------

Co-authored-by: github-actions <actions@users.noreply.github.com>

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -3,7 +3,9 @@ name: Continuous Delivery
 on:
   push:
     branches:
-      - release
+      - release/*
+    tags:
+      - "v*"
 
 jobs:
   release:
@@ -33,44 +35,44 @@ jobs:
         run: |
           git reset --hard ${{ github.sha }}
 
-      - name: Evaluate | Verify upstream has NOT changed
-        # Last chance to abort before causing an error as another PR/push was applied to
-        # the upstream branch while this workflow was running. This is important
-        # because we are committing a version change (--commit). You may omit this step
-        # if you have 'commit: false' in your configuration.
-        #
-        # You may consider moving this to a repo script and call it from this step instead
-        # of writing it in-line.
-        shell: bash
-        run: |
-          set +o pipefail
+      # - name: Evaluate | Verify upstream has NOT changed
+      #   # Last chance to abort before causing an error as another PR/push was applied to
+      #   # the upstream branch while this workflow was running. This is important
+      #   # because we are committing a version change (--commit). You may omit this step
+      #   # if you have 'commit: false' in your configuration.
+      #   #
+      #   # You may consider moving this to a repo script and call it from this step instead
+      #   # of writing it in-line.
+      #   shell: bash
+      #   run: |
+      #     set +o pipefail
 
-          UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
-          printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"
+      #     UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
+      #     printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"
 
-          set -o pipefail
+      #     set -o pipefail
 
-          if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
-              printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
-              exit 1
-          fi
+      #     if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
+      #         printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
+      #         exit 1
+      #     fi
 
-          git fetch "${UPSTREAM_BRANCH_NAME%%/*}"
+      #     git fetch "${UPSTREAM_BRANCH_NAME%%/*}"
 
-          if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
-              printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
-              exit 1
-          fi
+      #     if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
+      #         printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
+      #         exit 1
+      #     fi
 
-          HEAD_SHA="$(git rev-parse HEAD)"
+      #     HEAD_SHA="$(git rev-parse HEAD)"
 
-          if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
-              printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
-              printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
-              exit 1
-          fi
+      #     if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
+      #         printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
+      #         printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
+      #         exit 1
+      #     fi
 
-          printf '%s\n' "Verified upstream branch has not changed, continuing with release..."
+      #     printf '%s\n' "Verified upstream branch has not changed, continuing with release..."
 
       - name: Action | Semantic Version Release
         id: release
